spring.application.name=barberflow

spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.doc-expansion=none